[package]
authors = ["statiolake <statiolake@gmail.com>"]
name = "rsh"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.8.3"
log = "0.4.14"
itertools = "0.10.0"
rustyline = "8.2.0"

[dependencies.colored_print]
git = "https://github.com/statiolake/colored_print.git"
