[package]
authors = ["statiolake <statiolake@gmail.com>"]
name = "rsh"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.6.0"
log = "0.4.6"
itertools = "0.8.0"

[dependencies.colored_print]
git = "https://github.com/statiolake/colored_print.git"
